# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# executors: 
#   exec1:
#     docker:
#       – image: debian:stable-slim

# workflows
workflows:
  main:
    jobs:
      - build

# list of possible jobs and steps
jobs:
  build:
    # executor: exec1
    docker:
      - image: debian:stable-slim
    steps:
      - run:
          name: Installing dependencies
          command: |
            apt-get update
            apt-get install -y sudo gcc g++ zlib1g-dev libcurl4-openssl-dev m4 cmake git
            rm -rf /var/lib/apt/lists/*
      - checkout
      - run:
          name: run build_deps.sh
          command: ./build_deps.sh
      - run:
          name: Cmake config
          command: |
            mkdir -p build
            cd build
            cmake .. -DTINC_BUILD_TESTS=ON

      - run:
          name: Cmake build
          command: cmake -build .

